name: paragvae
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - setuptools
  - pytest
  - pytest-cov
  - numpy
  - scipy
  - scikit-learn
  - pyyaml
  - pandas
  - altair
  - vl-convert-python
variables:
  PYTHONPATH: src
